libraryDependencies += "org.apache.spark" % "spark-streaming-kafka-0-10_2.12" % "2.4.3"
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.4.3"
libraryDependencies += "org.apache.spark" %% "spark-streaming" % "2.4.3"
libraryDependencies +=  "org.apache.spark" %% "spark-sql" % "2.4.3"
libraryDependencies +=  "org.apache.spark" %% "spark-sql-kafka-0-10" % "2.4.3"
